use_field_init_shorthand = true

style_edition = "2024"

# Currently unstable options I'd like to set:
#
# imports_layout = "HorizontalVertical"
# indent_style = "Block"
# overflow_delimited_expr = true

