use_field_init_shorthand = true

# Temporarily don't use style edition 2024, to reduce likelihood of merge conflicts.
style_edition = "2021"

# Currently unstable options I'd like to set:
#
# imports_layout = "HorizontalVertical"
# indent_style = "Block"
# overflow_delimited_expr = true

