
# cargo-vet audits file

[[audits.alloca]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
version = "0.4.0"

[[audits.allocation-counter]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.8.1"

[[audits.arcstr]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "1.1.5"

[[audits.array-init-cursor]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.2.1"

[[audits.async_fn_traits]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.1.1"

[[audits.base64]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.21.2"

[[audits.bytes]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "1.11.0 -> 1.11.1"

[[audits.cassowary]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.3.0"

[[audits.compact_str]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.8.1 -> 0.9.0"

[[audits.criterion]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.6.0 -> 0.7.0"

[[audits.criterion]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
delta = "0.7.0 -> 0.8.0"

[[audits.criterion-plot]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.5.0 -> 0.6.0"

[[audits.displaydoc]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.2.4"

[[audits.displaydoc]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.2.5"

[[audits.dot_vox]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "5.1.1 -> 5.2.0"

[[audits.euclid]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.22.9"

[[audits.float-cmp]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.9.0 -> 0.10.0"

[[audits.flume]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.11.0 -> 0.12.0"

[[audits.foldhash]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.1.5 -> 0.2.0"

[[audits.gltf-derive]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "1.2.0 -> 1.4.1"

[[audits.half]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "2.6.0 -> 2.7.1"

[[audits.imgref]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "1.10.1"

[[audits.indexmap]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "2.10.0 -> 2.11.4"

[[audits.kasuari]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.4.11"

[[audits.line-clipping]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.3.5"

[[audits.log]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.4.26 -> 0.4.27"

[[audits.mint]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.5.9"

[[audits.mutants]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.0.3"

[[audits.mutants]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.0.3 -> 0.0.4"

[[audits.ordered-float]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "4.2.0 -> 5.0.0"

[[audits.oxipng]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
version = "9.1.3"

[[audits.oxipng]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
delta = "9.1.3 -> 10.0.0"

[[audits.page_size]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
version = "0.6.0"

[[audits.png-decoder]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
version = "0.1.1"
notes = """
It allocates an amount of memory determined by the input image
(using `Vec::with_capacity()`) without checks, so a malicious image
could DoS via excessive memory use (zip bomb attack).
"""

[[audits.png-decoder]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.1.1 -> 0.2.0"

[[audits.pretty_assertions]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "1.4.0"

[[audits.priority-queue]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
version = "2.5.0"

[[audits.ratatui]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.24.0"

[[audits.ratatui]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.26.1"

[[audits.ratatui]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.29.0 -> 0.30.0"

[[audits.ratatui-core]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.rataui-crossterm]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.rectangle-pack]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.4.2"

[[audits.resource]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.5.0 -> 0.6.0"

[[audits.resource_list_proc_macro]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.6.0"

[[audits.rstest]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
delta = "0.25.0 -> 0.26.1"

[[audits.rstest_macros]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
delta = "0.25.0 -> 0.26.1"

[[audits.snapbox]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.6.24 -> 1.0.0"

[[audits.stl_io]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.7.0"

[[audits.stl_io]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.7.0 -> 0.8.1"

[[audits.stl_io]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.8.1 -> 0.10.0"

[[audits.sync_wrapper]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "1.0.1"

[[audits.sync_wrapper]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "1.0.1 -> 1.0.2"

[[audits.tempfile]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "3.17.1 -> 3.19.1"

[[audits.toml_datetime]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
delta = "0.7.5+spec-1.1.0 -> 1.0.0+spec-1.1.0"

[[audits.toml_edit]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-run"
delta = "0.24.1+spec-1.1.0 -> 0.25.2+spec-1.1.0"

[[audits.trycmd]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.15.4 -> 1.0.0"

[[audits.visibility]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.1.1"

[[audits.web-time]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
version = "0.2.3"

[[audits.web-time]]
who = "Kevin Reid <kpreid@switchb.org>"
criteria = "safe-to-deploy"
delta = "0.2.3 -> 1.0.0"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2026-03-08"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2026-03-08"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2026-03-08"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2026-03-08"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2026-03-08"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2026-03-08"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-28"
end = "2026-03-08"

[[trusted.clap_derive]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2026-03-08"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-04-15"
end = "2026-03-08"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2026-03-08"

[[trusted.dunce]]
criteria = "safe-to-deploy"
user-id = 988 # Kornel (kornelski)
start = "2019-03-14"
end = "2026-04-26"

[[trusted.emath]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2024-12-16"
end = "2026-03-11"

[[trusted.exhaust]]
criteria = "safe-to-deploy"
user-id = 98157 # Kevin Reid (kpreid)
start = "2022-02-15"
end = "2026-03-08"

[[trusted.exhaust-macros]]
criteria = "safe-to-deploy"
user-id = 98157 # Kevin Reid (kpreid)
start = "2022-02-15"
end = "2026-03-08"

[[trusted.imgref]]
criteria = "safe-to-deploy"
user-id = 988 # Kornel (kornelski)
start = "2019-08-20"
end = "2026-04-26"

[[trusted.is-terminal]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2022-01-22"
end = "2026-03-25"

[[trusted.is_terminal_polyfill]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2024-05-02"
end = "2026-03-08"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2026-03-25"

[[trusted.manyfmt]]
criteria = "safe-to-deploy"
user-id = 98157 # Kevin Reid (kpreid)
start = "2023-10-07"
end = "2026-03-08"

[[trusted.nosy]]
criteria = "safe-to-deploy"
user-id = 98157 # Kevin Reid (kpreid)
start = "2024-12-19"
end = "2026-03-08"

[[trusted.range-alloc]]
criteria = "safe-to-deploy"
user-id = 53780 # Connor Fitzgerald (cwfitzgerald)
start = "2023-02-10"
end = "2026-03-08"

[[trusted.re_arrow2]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2024-01-22"
end = "2026-03-11"

[[trusted.re_arrow2]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2024-01-22"
end = "2026-03-08"

[[trusted.re_arrow_util]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2025-02-05"
end = "2026-03-11"

[[trusted.re_arrow_util]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2025-02-05"
end = "2026-03-08"

[[trusted.re_build_info]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-03-06"
end = "2026-03-11"

[[trusted.re_build_info]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-03-06"
end = "2026-03-08"

[[trusted.re_build_tools]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-07-05"
end = "2026-03-11"

[[trusted.re_build_tools]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-07-05"
end = "2026-03-08"

[[trusted.re_byte_size]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2025-02-05"
end = "2026-03-11"

[[trusted.re_byte_size]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2025-02-05"
end = "2026-03-08"

[[trusted.re_case]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2024-06-10"
end = "2026-03-11"

[[trusted.re_case]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2024-06-10"
end = "2026-03-08"

[[trusted.re_chunk]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2024-06-10"
end = "2026-03-11"

[[trusted.re_chunk]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2024-06-10"
end = "2026-03-08"

[[trusted.re_error]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_error]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_format]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_format]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_format_arrow]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2024-05-07"
end = "2026-03-11"

[[trusted.re_format_arrow]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2024-05-07"
end = "2026-03-08"

[[trusted.re_grpc_client]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2024-11-11"
end = "2026-04-26"

[[trusted.re_grpc_server]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2025-02-05"
end = "2026-04-26"

[[trusted.re_log]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_log]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_log_encoding]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-04-19"
end = "2026-03-11"

[[trusted.re_log_encoding]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-04-19"
end = "2026-03-08"

[[trusted.re_log_types]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_log_types]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_memory]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_memory]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_protos]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2024-11-11"
end = "2026-03-11"

[[trusted.re_protos]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2024-11-11"
end = "2026-03-08"

[[trusted.re_sdk]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_sdk]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_sdk_comms]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_sdk_comms]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_smart_channel]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_smart_channel]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_sorbet]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2025-02-05"
end = "2026-03-11"

[[trusted.re_sorbet]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2025-02-05"
end = "2026-03-08"

[[trusted.re_span]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2025-07-01"
end = "2026-09-16"

[[trusted.re_string_interner]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_string_interner]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_tracing]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-07-05"
end = "2026-03-11"

[[trusted.re_tracing]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-07-05"
end = "2026-03-08"

[[trusted.re_tuid]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-11"

[[trusted.re_tuid]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-02-12"
end = "2026-03-08"

[[trusted.re_types]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-07-05"
end = "2026-03-11"

[[trusted.re_types]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-07-05"
end = "2026-03-08"

[[trusted.re_types_builder]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-07-05"
end = "2026-03-11"

[[trusted.re_types_builder]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-07-05"
end = "2026-03-08"

[[trusted.re_types_core]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2023-10-26"
end = "2026-03-11"

[[trusted.re_types_core]]
criteria = "safe-to-run"
user-id = 197939 # rerun.io (rerunio)
start = "2023-10-26"
end = "2026-03-08"

[[trusted.re_uri]]
criteria = "safe-to-deploy"
user-id = 197939 # rerun.io (rerunio)
start = "2025-04-07"
end = "2026-04-26"

[[trusted.rendiff]]
criteria = "safe-to-deploy"
user-id = 98157 # Kevin Reid (kpreid)
start = "2023-05-06"
end = "2026-03-08"

[[trusted.rgb]]
criteria = "safe-to-deploy"
user-id = 988 # Kornel (kornelski)
start = "2019-02-26"
end = "2026-04-26"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2026-03-25"

[[trusted.security-framework]]
criteria = "safe-to-deploy"
user-id = 988 # Kornel (kornelski)
start = "2019-02-27"
end = "2026-04-26"

[[trusted.security-framework-sys]]
criteria = "safe-to-deploy"
user-id = 988 # Kornel (kornelski)
start = "2019-02-27"
end = "2026-04-26"

[[trusted.serde_spanned]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-01-20"
end = "2026-03-08"

[[trusted.snapbox]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-03-07"
end = "2026-03-08"

[[trusted.snapbox-macros]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-03-07"
end = "2026-03-08"

[[trusted.toml]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-12-14"
end = "2026-03-08"

[[trusted.toml_datetime]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-10-21"
end = "2026-03-08"

[[trusted.toml_edit]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2026-03-08"

[[trusted.trycmd]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-11-05"
end = "2026-03-08"

[[trusted.urlencoding]]
criteria = "safe-to-deploy"
user-id = 988 # Kornel (kornelski)
start = "2020-06-17"
end = "2026-04-26"

[[trusted.wgpu]]
criteria = "safe-to-deploy"
user-id = 53780 # Connor Fitzgerald (cwfitzgerald)
start = "2022-07-01"
end = "2026-03-08"

[[trusted.wgpu-core]]
criteria = "safe-to-deploy"
user-id = 53780 # Connor Fitzgerald (cwfitzgerald)
start = "2022-07-01"
end = "2026-03-12"

[[trusted.wgpu-hal]]
criteria = "safe-to-deploy"
user-id = 53780 # Connor Fitzgerald (cwfitzgerald)
start = "2022-07-01"
end = "2026-03-12"

[[trusted.winnow]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2026-03-08"

[[trusted.yield-progress]]
criteria = "safe-to-deploy"
user-id = 98157 # Kevin Reid (kpreid)
start = "2023-08-23"
end = "2026-03-08"
